// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package types

import (
	"encoding/json"
	"errors"
)

func (e ExtendedHeader) MarshalJSON() ([]byte, error) {
	type ExtendedHeader struct {
		Signature Signature `json:"signature"       gencodec:"required"`
	}
	var enc ExtendedHeader
	enc.Signature = e.Signature
	return json.Marshal(&enc)
}

func (e *ExtendedHeader) UnmarshalJSON(input []byte) error {
	type ExtendedHeader struct {
		Signature *Signature `json:"signature"       gencodec:"required"`
	}
	var dec ExtendedHeader
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.Signature == nil {
		return errors.New("missing required field 'signature' for ExtendedHeader")
	}
	e.Signature = *dec.Signature
	return nil
}
